### ISSUE TITLE
在深色/浅色模式切换时，插件似乎不能适配

### ISSUE THREAD

**Issue by QAQdev** [TonyCrane/mkdocs-changelog-plugin#3]
我注意到css的background设置时是用了导航栏的颜色，我想要自定义，于是我覆盖原有css，但是为了支持深色/浅色模式，我写了如下css：
```css
@media(prefers-color-scheme: light) {
    .timeline-content::before {
        content: "";
        position: absolute;
        width: 20px;
        height: 20px;
        transform: rotate(45deg);
        background-color: #aaaaaa;
        left: -10px;
        top: calc(50% - 10px);
        box-shadow: var(--md-shadow-z2);
    }
    .timeline-card {
        position: relative;
        display: -ms-flexbox;
        display: flex;
        -ms-flex-direction: column;
        flex-direction: column;
        min-width: 0;
        word-wrap: break-word;
        background-image: linear-gradient(to top, #cfd9df 0%, #e2ebf0 100%);
        /* background-image: linear-gradient(to top, #d5d4d0 0%, #d5d4d0 1%, #eeeeec 31%, #efeeec 75%, #e9e9e7 100%); */
        border-radius: .25rem;
        padding-top: 10px;
        padding-bottom: 10px;
        padding-left: 15px;
        padding-right: 10px;
        box-shadow: var(--md-shadow-z2);
    }
}
```
但这样并没有覆盖原有的css样式，不知道有没有什么好的办法可以做到适配深色/浅色模式的切换？

**Comment by TonyCrane** [comment]
https://squidfunk.github.io/mkdocs-material/setup/changing-the-colors/#custom-color-schemes

看一下这里，默认的深色模式应该可以直接用 `[data-md-color-scheme="slate"]` 加在前面，浅色模式可以用 default，或者不加这个 selector 但放前面（不然会把前面的深色模式覆盖）

以及覆盖的话不用写那么多的，只留一个 background-color 就够了，比如：

```css
[data-md-color-scheme="slate"] .timeline-card {
    background-color: #aaaaaa;
}
[data-md-color-scheme="slate"] .timeline-content::before {
    background-color: #aaaaaa;
}

[data-md-color-scheme="default"] .timeline-card {
    background-color: #bbbbbb;
}
[data-md-color-scheme="default"] .timeline-content::before {
    background-color: #bbbbbb;
}
```
